# Generated by Django 5.1.6 on 2025-02-18 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ScoplantUserPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date_Log', models.DateField(auto_now=True)),
                ('Time_Log', models.CharField(max_length=10)),
                ('Battery_Log', models.CharField(max_length=10)),
                ('Lux_Log', models.CharField(max_length=10)),
                ('Humidity_Log', models.CharField(max_length=10)),
                ('Temperature_Log', models.CharField(max_length=10)),
                ('SoilMoisture_Log', models.CharField(max_length=10)),
                ('SoilTemperature_Log', models.CharField(max_length=10)),
                ('EC_Log', models.CharField(max_length=10)),
                ('PH_Log', models.CharField(max_length=10)),
                ('airAlt_Log', models.CharField(max_length=10)),
                ('airP_Log', models.CharField(max_length=10)),
                ('airTemp_Log', models.CharField(max_length=5)),
                ('id_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScoplantUserPanel.adddeviceinfo')),
            ],
        ),
    ]
